openapi: 3.1.0
info:
  title: Dihya RGPD GraphQL API
  description: |
    Documentation interactive pour l’API GraphQL RGPD : export, anonymisation, suppression, consentement, multilingue (13 langues), audit, plugins, sécurité, auditabilité, extensible.
    - Expose les mutations, queries, types, autorisations, plugins, auditabilité, fallback IA.
    - Internationalisation dynamique (fr, en, ar, amazigh, de, zh, ja, ko, nl, he, fa, hi, es)
    - Sécurité JWT, CORS, WAF, anti-DDOS, auditabilité, anonymisation, plugins, fallback IA.
    - Compatible GraphQL Playground, Altair, Postman, Swagger UI (description), Redoc.
  version: "1.0.0"
servers:
  - url: /api/rgpd/graphql
    description: API GraphQL RGPD
paths:
  /graphql:
    post:
      summary: Endpoint GraphQL RGPD
      description: |
        Endpoint unique pour toutes les requêtes GraphQL RGPD : export, suppression, consentement, audit, plugins, multilingue.
      tags:
        - GraphQL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: Résultat de la requête GraphQL
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                  errors:
                    type: array
                    items:
                      type: object
        '403':
          description: Action non autorisée
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        '422':
          description: Erreur de validation
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
