# Azure Pipelines pour Dihya – Audit ultra avancé
# Exécute tous les audits et archive les rapports globaux (CSV/JSON)

trigger:
  branches:
    include:
      - main
      - master
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      pip install openpyxl PyPDF2 toml pyyaml jq || true
      chmod +x Dihya/backend/audit/scripts/run_all_audits.sh || true
      chmod +x Dihya/backend/audit/scripts/ci_audit_job.sh || true
      cd Dihya/backend/audit/scripts
      ./run_all_audits.sh || true
      ./ci_audit_job.sh || true
      pytest test_audit_scripts.py --maxfail=1 --disable-warnings --tb=short
      if [ -f package.json ]; then npm install jest --no-save || true; fi
      if [ -f test_audit_scripts_node.js ]; then npx jest test_audit_scripts_node.js || node test_audit_scripts_node.js; fi
      bash test_audit_scripts_shell.sh
    displayName: 'Exécute tous les audits Dihya + tests unitaires'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'Dihya/backend/audit/reports'
      ArtifactName: 'audit-reports'
      publishLocation: 'Container'
